### ISSUE TITLE
Not all YARD literals are handled (true, false, nil)

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#10]
https://www.rubydoc.info/gems/yard/file/docs/Tags.md#Literals

`void` is currently handled fine, but `true`, `false`, and `nil` are not. I assume `self` also isn't handled, but I don't have an example of that.

Input:

```ruby
# Always returns true.
# @return [true]
def matches?()
  true
end
```

Output:

```ruby
# sord warn - true is probably not a type, but using anyway
sig { params().returns(true) }
def matches?() end
```

**Comment by AaronC81** [comment]
Thanks a bunch for all of your recent PRs!

I'm not sure what the elegant way to implement this is, on Sorbet's end. As far as I know there isn't a T::True or T::False, but only T::Boolean. (Correct me if I'm wrong!) As one option, should `true` be converted to a Sorbet type of `TrueClass`? I feel like this looks a bit ugly...

```ruby
sig { params().returns(TrueClass) }
def matches?() end
```

Also, in my opinion, a good way to handle `nil` would be to wrap the rest of that thing's type in `T.nilable`.

**Comment by connorshea** [comment]
I'm not sure how to handle this, I was thinking maybe just replacing `true` and/or `false` with `T::Boolean`? I know my example is only able to return `true`, but I'm not sure that's actually relevant for the type signature. It doesn't care _what_ gets returned, just its type. Plus, I'd say a method that can only return `true` or only return `false` is probably an edge-case.

And yeah I agree with the `T.nilable` handling.

**Comment by AaronC81** [comment]
These should all now be implemented. `true` or `false` will become `T::Boolean`, any type with `nil` becomes a `T.nilable`, and `self` looks up the containing namespace and uses its name.
