### ISSUE TITLE
Initialize methods should return void

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#105]
**Is your feature request related to a problem? Please describe.**
Sord generates a type signature for initialize methods that returns the parent class, this isn’t what’s recommended by the Sorbet docs. The docs recommend returning void to discourage users from using initialize directly.

**Describe the solution you'd like**
Sord should generate initialize methods with void return types. We could also potentially have a flag that would return to the current behavior? (Or vice versa)

https://sorbet.org/docs/faq#how-do-i-write-a-signature-for-initialize

**Comment by cmur2** [comment]
This sounds like a very sensible suggestion to avoid having to put `# @return [void]` manually onto every `def initialize` as in https://github.com/AaronC81/sord/blob/master/lib/sord/rbi_generator.rb#L30.
