### ISSUE TITLE
Add --clean flag to output rbi file without comments

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#13]
**Is your feature request related to a problem? Please describe.**
I want to use the generated `rbi` file, so I want to be able to create one without all the comments.

**Describe the solution you'd like**
I'd like sord to be able to output an `rbi` file without all the comments, so I can use it for sorbet-typed or in a gem.

I'm not in love with `--clean` as the name, if you can come up with a better name I'd be fine with that.

What's currently generated:

```ruby
# sord omit - no YARD type given for "token", using T.untyped
# sord omit - no YARD type given for "server_id", using T.untyped
# sord omit - no YARD type given for "name", using T.untyped
# sord omit - no YARD type given for "colour", using T.untyped
# sord omit - no YARD type given for "hoist", using T.untyped
# sord omit - no YARD type given for "mentionable", using T.untyped
# sord omit - no YARD type given for "packed_permissions", using T.untyped
# sord omit - no YARD type given for "reason", using T.untyped
sig { params(token: T.untyped, server_id: T.untyped, name: T.untyped, colour: T.untyped, hoist: T.untyped, mentionable: T.untyped, packed_permissions: T.untyped, reason: T.untyped).void }
def create_role(token, server_id, name, colour, hoist, mentionable, packed_permissions, reason = nil); end
```

What I'd like:

```ruby
sig { params(token: T.untyped, server_id: T.untyped, name: T.untyped, colour: T.untyped, hoist: T.untyped, mentionable: T.untyped, packed_permissions: T.untyped, reason: T.untyped).void }
def create_role(token, server_id, name, colour, hoist, mentionable, packed_permissions, reason = nil); end
```

**Describe alternatives you've considered**
Manually cleaning up the comments, but this feels silly :)

**Additional context**
It'd also be nice to have linebreaks between methods for readability. Maybe also a configurable limit where the signature becomes a block when there are more than `n` params (I'm not sure if there should be a separate issue for formatting?), e.g:

```ruby
sig do
  params(
    token: T.untyped,
    server_id: T.untyped,
    name: T.untyped,
    colour: T.untyped,
    hoist: T.untyped,
    mentionable: T.untyped,
    packed_permissions: T.untyped,
    reason: T.untyped
  ).void
end
def create_role(token, server_id, name, colour, hoist, mentionable, packed_permissions, reason = nil); end
```

**Comment by AaronC81** [comment]
I'm currently in the process of implementing the first part of this, and just fleshing out the CLI in general, using Commander.

The second part (re. breaking up parameter lists) could probably be done by simply applying a decent beautifier to the output RBI. I'll experiment with that and see how it goes.

**Comment by AaronC81** [comment]
Implemented in 5c6d22f06b98256be6975ba36b1da64c7854304e as `--no-comments` (and corresponding `--comments`) switch!

**Comment by AaronC81** [comment]
Reopening because I didn't implement line breaks in that commit

**Comment by AaronC81** [comment]
The unfinished part of this is now #30, so closing this one.
