### ISSUE TITLE
Support for &block

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#14]
**Describe the bug**
Methods with a `&block` parameter end up with an invalid signature in the generated rbi.

**To Reproduce**
This is the input code (most is the YARD docs are irrelevant to the issue, I've already cut out a lot of the docs for this method):

```ruby
# Adds a new command to the container.
# @param name [Symbol, Array<Symbol>] The name of the command to add, or an array of multiple names for the command
# @param attributes [Hash] The attributes to initialize the command with.
# @option attributes [Integer] :permission_level The minimum permission level that can use this command, inclusive.
#   See {CommandBot#set_user_permission} and {CommandBot#set_role_permission}.
# @yield The block is executed when the command is executed.
# @yieldparam event [CommandEvent] The event of the message that contained the command.
# @note `LocalJumpError`s are rescued from internally, giving bots the opportunity to use `return` or `break` in
#   their blocks without propagating an exception.
# @return [Command] The command that was added.
def command(name, attributes = {}, &block)
  # code
end
```

**Expected behavior**
It should match the block example in the sorbet documentation: https://sorbet.org/docs/sigs#params-annotating-parameter-types

It should probably look like this, where the parameter name is `block` instead of `&block`:

```ruby
sig { params(name: T.any(Symbol, T::Array[Symbol]), attributes: Hash, block: T.untyped).returns(Command) }
def command(name, attributes = {}, &block); end
```

**Actual behavior**
It generates `&block: T.untyped` in the signature, which is invalid:

```ruby
sig { params(name: T.any(Symbol, T::Array[Symbol]), attributes: Hash, &block: T.untyped).returns(Command) }
def command(name, attributes = {}, &block); end
```

**Comment by AaronC81** [comment]
I noticed this yesterday when trying it on some existing gems. As you've suggested, just removing the `&` is enough to make it _valid_, but a nice future goal would be to have it actually generate a block type using `yieldparam` and `yieldreturn`.
