### ISSUE TITLE
Handling duck typing

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#15]
**Is your feature request related to a problem? Please describe.**
Currently, duck-typed parameters don't work and output a `SORD_ERROR`.

Input: 
```ruby
# Adds a new custom emoji on this server.
# @param name [String] The name of emoji to create.
# @param image [String, #read] A base64 encoded string with the image data, or an object that responds to `#read`, such as `File`.
# @param roles [Array<Role, String, Integer>] An array of roles, or role IDs to be whitelisted for this emoji.
# @param reason [String] The reason the for the creation of this emoji.
# @return [Emoji] The emoji that has been added.
def add_emoji(name, image, roles = [], reason: nil)
  # code
end
```

Output:

```ruby
# sord warn - "#read" does not appear to be a type
# sord omit - no YARD type given for "reason:", using T.untyped
sig { params(name: String, image: T.any(String, SORD_ERROR_read), roles: T::Array[Role, String, Integer], reason: T.untyped).returns(Emoji) }
def add_emoji(name, image, roles = [], reason: nil); end
```

[YARD supports them](https://www.rubydoc.info/gems/yard/file/docs/Tags.md#Duck-Types) (kind of), but Sorbet doesn't really have a concept for duck types as far as I know. I guess they should be treated as untyped?

**Describe the solution you'd like**
I'm not really sure, there are a few options I can think of:
- Add a warning (`[DUCK ]`?) and make the type of the parameter `T.untyped`.
- Not allowing duck-typing, this is essentially where we're at right now, and it's not ideal.

**Comment by AaronC81** [comment]
I've been pondering how to approach this - it's a much more common pattern than I thought.

I like the idea of the `[DUCK ]` logging category. `T.untyped` also seems to be the most practical option.

I was thinking that `interface!` could be used somehow to generate an interface automatically which only fits objects defining that method (e.g. `#to_s`). Unfortunately, interfaces must be implemented explicitly by each class, so this wouldn't really work.

**Comment by connorshea** [comment]
Yeah, IIRC at the end of the Sorbet talk at RubyKaigi 2019 they answer a question about ducktyping and essentially say it's unsupported (it's during the Q&A at the end of the talk if you want to watch it).

**Comment by AaronC81** [comment]
It's a tad unfortunate - while explicitly-implemented interfaces are fine and many languages get by with them, a system like Haskell's typeclasses or Go's implicitly-implemented interfaces could be really powerful in some situations.

**Comment by AaronC81** [comment]
I've added the `[DUCK ]` logging and `T.untyped` replacement.

I'm tempted to leave the issue open though, since it feels like there might be a better solution to this issue which is able to somehow validate that the method specified by the duck type is available.

**Comment by connorshea** [comment]
You can also do one other weird thing with duck typing, `#foo & #bar`:

```ruby
# @return [Array<IO>, Array<#puts & #flush>] the streams the logger should write to.
attr_accessor :streams
```

```ruby
# sord warn - "#puts & #flush" does not appear to be a type
# sord infer - inferred type of parameter "value" as T.any(T::Array[IO], T::Array[SORD_ERROR_putsflush]) using getter's return type
# sord warn - "#puts & #flush" does not appear to be a type
sig { params(value: T.any(T::Array[IO], T::Array[SORD_ERROR_putsflush])).returns(T.any(T::Array[IO], T::Array[SORD_ERROR_putsflush])) }
def streams=(value); end
```

I'm not really sure if that's valid YARD, though. 🤷‍♂

**Comment by connorshea** [comment]
It seems like it's not _technically_ valid YARD, it seems like it comes from here: https://stackoverflow.com/questions/9126802/document-duck-types-with-multiple-methods-in-yard

I'm not sure how common it'd be to have YARD docs that use this specific syntax.

**Comment by AaronC81** [comment]
I believe this is now covered by #38 and #42.
