### ISSUE TITLE
Literal symbols aren't handled by Sord

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#26]
**Describe the bug**
I'm not actually sure if this is valid YARD, it may not be. If it isn't, we can close this.

For a `Paginator`, `direction` can either be `:up` or `:down`. Sord isn't able to determine a type from this, maybe it should be able to?

**To Reproduce**
```ruby
# Creates a new {Paginator}
# @param limit [Integer] the maximum number of items to request before stopping
# @param direction [:up, :down] the order in which results are returned in
# @yield [Array, nil] the last page of results, or nil if this is the first iteration.
#   This should be used to request the next page of results.
# @yieldreturn [Array] the next page of results
def initialize(limit, direction, &block)
  # code
end
```

**Expected behavior**
```ruby
sig { params(limit: Integer, direction: Symbol, block: T.untyped).returns(Paginator) }
def initialize(limit, direction, &block); end
```

**Actual behavior**
`SORD_ERROR_up` and `SORD_ERROR_down`:

```ruby
# sord warn - ":up" does not appear to be a type
# sord warn - ":down" does not appear to be a type
sig { params(limit: Integer, direction: T.any(SORD_ERROR_up, SORD_ERROR_down), block: T.untyped).returns(Paginator) }
def initialize(limit, direction, &block); end
```

**Additional information**
I imagine this'd also happen when given any kinds of literals, e.g. if an attribute could only ever be `1`, `2`, `3`, `4`, or `5`.

**Comment by AaronC81** [comment]
This seems like a good feature, and it is indeed valid YARD:
![image](https://user-images.githubusercontent.com/3321773/59970187-d92fe980-9557-11e9-9dc5-f56bf97e7b79.png)

**Comment by AaronC81** [comment]
I've been able to make this recognise symbol, string, integer and float literals by trying `YAML.load` on any unrecognised types.

**Comment by connorshea** [comment]
Nice!
