### ISSUE TITLE
Git tags and Changelog.md

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#29]
**Is your feature request related to a problem? Please describe.**
It'd be nice if the sord repo had git tags for each version (I think RubyGems might create them automatically when you publish a gem? `git push --tags` pushes any local tags to the remote), it'd also be nice to have a Changelog file in the repo. :)

**Describe the solution you'd like**
I usually just use the format from [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) (e.g. https://github.com/connorshea/vscode-ruby-test-adapter/blob/master/CHANGELOG.md), I'd recommend it.

**Comment by AaronC81** [comment]
Unfortunately there don't seem to be any tags from RubyGems, but I assume I can go back and add them? (I've never used tags before.) I'll also create a changelog by looking back through commits.

**Comment by connorshea** [comment]
Yeah, just find the commit where you bumped the version and create a tag like `git tag -a v0.1.0 sha123`

https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by connorshea** [comment]
🥳 thanks!
