### ISSUE TITLE
If Sord finds 0 objects, suggest generating YARD docs

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#31]
**Is your feature request related to a problem? Please describe.**
If I haven't run `yard` first to generate the YARD files, Sord will just output 0 objects.

**Describe the solution you'd like**
If this happens, I'd like to have Sord tell me a possible solution: running `yard` to generate the documentation. Something like "Are you sure you've generated the YARD docs for this project? Run 'yard' to generate the YARD docs."

**Additional context**
Is there any way to check whether the YARD docs are the most recent version of the repository? It'd be nice to at least give the user a warning in that case. For a while I was using an older version of discordrb's YARD docs, because I'm an idiot :)

**Comment by AaronC81** [comment]
I've added the "0 objects" part of this, but I'm not sure how to approach "older version" part is possible. Sord could invoke YARD with a different database path and compare that with `.yardoc` using `yard diff`, but for large projects this would probably be quite slow as it would require docs to be generated on each run.

I'll leave this open in the likely event there's a much better way I haven't thought of.

**Comment by connorshea** [comment]
🤔 We could make the default involve generating yard docs with a flag to override that functionality if the user doesn’t want/need to regenerate them.

**Comment by AaronC81** [comment]
Sounds like a good idea to me.

**Comment by AaronC81** [comment]
Does this seem like a reasonable way of implementing this to you? I'm always hesitant about shelling-out to other tools.

https://github.com/AaronC81/sord/blob/generate-yard/exe/sord#L24-L32

**Comment by connorshea** [comment]
Seems fine to me, I don’t think it should cause any problems.

**Comment by AaronC81** [comment]
Great - merged!
