### ISSUE TITLE
Method tag with no return type

### ISSUE THREAD

**Issue by alloy** [AaronC81/sord#35]
**Describe the bug**

Invoking `sord` on `graphql-ruby` docs leads to runtime crash.

**To Reproduce**

```
gem install sord
git clone https://github.com/rmosolgo/graphql-ruby.git
cd graphql-ruby
git ch v1.9.6
bundle install
bundle exec yard
sord graphql.rbi
```

**Expected behavior**

The program finished successfully.

**Actual behavior**

```
[ERROR] undefined method `first' for nil:NilClass
         /Users/eloy/.gem/ruby/2.5.3/gems/commander-4.4.7/lib/commander/user_interaction.rb:359:in `method_missing'
         /Users/eloy/.gem/ruby/2.5.3/gems/sord-0.6.0/lib/sord/rbi_generator.rb:120:in `block in add_methods'
```

**Additional information**

I was able to get `sord` to successfully finish by changing [this line](https://github.com/AaronC81/sord/blob/8a19d6dac93fcb394aa2c8fb095fbc3a2b09d090/lib/sord/rbi_generator.rb#L126) to:

```ruby
elsif return_tags.length == 1 && return_tags.first.types&.first&.downcase == "void"
```

However, I have spent all of 5 seconds on this after first installing `sord`, so not sure if this leads to the desired behaviour.

**Comment by AaronC81** [comment]
I haven't been able to run this yet, but I _think_ this might be a result of a codebase-wide false assumption that, if a `@param` or `@return` is specified, it will always have a type. Thanks for the report - I'll look into fixing this shortly!
