### ISSUE TITLE
Not handling Arrays or Hashes without type name

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#43]
**Describe the bug**
Sord doesn't correctly handle `<String>` (should be equivalent to `Array<String>`) or `{String => true}` (equivalent to `Hash{String => true}`)

I tested sord with [zeitwerk](https://github.com/fxn/zeitwerk) and discovered this issue.

**To Reproduce**
```ruby
# Absolute paths of files or directories that have to be preloaded.
#
# @private
# @return [<String>]
attr_reader :preloads
```

**Expected behavior**
```ruby
sig { returns(T::Array[String]) }
def preloads(); end
```

**Actual behavior**
```ruby
# sord warn - "<String>" does not appear to be a type
sig { returns(SORD_ERROR_String) }
def preloads(); end
```

**Additional information**
The type parser seems to suggest these are valid, so we should try to support them.

**Comment by connorshea** [comment]
Tested a view gems to see what errors were left to fix:
- [addressable](https://github.com/sporkmonger/addressable) - no SORD_ERRORs
- [gitlab api gem](https://github.com/NARKOZ/gitlab) - no SORD_ERRORs
- [zeitwerk](https://github.com/fxn/zeitwerk) - this issue
- [yard](https://github.com/lsegal/yard) - solved by #42
- [rspec-core](https://github.com/rspec/rspec-core) - 2 SORD_ERRORs, most notably [this one caused by a linebreak](https://github.com/rspec/rspec-core/blob/7b6b9c3f2e2878213f97d6fc9e9eb23c323cfe1c/lib/rspec/core/notifications.rb#L101), maybe we can fix this by just filtering out any `\n`s?
- [bundler](https://github.com/bundler/bundler) - 13 SORD_ERRORs where they're pretty much all this issue
- [haml](https://github.com/haml/haml) - 33 SORD_ERRORs mostly due to this issue or some weird invalid stuff like `String or nil`
- [rouge](https://github.com/rouge-ruby/rouge) - 302 SORD_ERRORs, all of which are caused by `unsupported generic type "Class" in "Class<Rouge::Lexer>`
- [aws-sdk-s3](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3) - 12 SORD_ERRORs, all of these just seem to be weird invalid things the gem does.

**Comment by AaronC81** [comment]
That's a really useful insight into where Sord is now! Rouge's issue can be sorted by translating `Class<X>` into `T.class_of(X)`; I'll create an issue for that.

**Comment by AaronC81** [comment]
This should now be implemented - Zeitwerk no longer has any errors related to this!
