### ISSUE TITLE
Tests for RbiGenerator

### ISSUE THREAD

**Issue by AaronC81** [AaronC81/sord#45]
**Is your feature request related to a problem? Please describe.**
There aren't any tests for `Sord::RbiGenerator`, which makes ensuring you haven't broken anything difficult.

**Describe the solution you'd like**
A decent test suite needs to be written for `RbiGenerator`.

**Additional context**
Writing tests for this may be somewhat tricky, because they rely heavily on the contents of the YARD registry. It might be necessary to create a tiny framework to generate 'stub' YARD registries for each test.

**Comment by connorshea** [comment]
It may be worth looking at how steep does tests: https://github.com/soutaro/steep/commit/3b690365cc02b7b94f4a356228a26b424859a1a5

Essentially, if we can put Ruby code in HEREDOCs, send that through YARD, and then give Sord the Yard Registry that’s created, that’d be a pretty big win.

Other projects that might be worth looking at are rubocop, rufo, and I guess yard itself?

**Comment by connorshea** [comment]
Of course, my idea has the downside of being significantly slower because the tests have to run all the way through YARD, which is not exactly fast. You could also just create static fixtures for the YARD registry objects and give Sord those to test on.

**Comment by AaronC81** [comment]
Thanks for these suggestions - I used the same technique which YARD itself does, which is to clear the registry before each test and then use `YARD.parse_string` to load a new code block into the registry.

The tests are now on the `formatting` branch, which I'll merge when the comment indentation issues mentioned in #30 have been ironed out.

**Comment by AaronC81** [comment]
Added when merging #30

**Comment by connorshea** [comment]
Nice!
