### ISSUE TITLE
Some methods (without YARD docblock?) are given `sig { void }` and it's incorrect. 

### ISSUE THREAD

**Issue by manhhung741** [AaronC81/sord#49]
**Describe the bug**
Methods without YARD docblock is given `sig { void }` and it's incorrect. 
(Note: I'm not familiar with YARD so my understanding of what a YARD docblock is may be wrong)

**To Reproduce**
1. Git clone Rails
2. `cd rails/activerecord/`
3. Run sord activerecord.rbi
4. Checkout activerecord.rbi, search for `changed_attribute_names_to_save`
5. Confirm that it has `{ void }` signature
Look at the implementation, it is wrong:
https://github.com/rails/rails/blob/3b2ba908bad6962be8b1b0c368a97721dc864eb4/activerecord/lib/active_record/attribute_methods/dirty.rb
I observe this happens to a lot of methods.

**Expected behavior**
It should best omit the method
Or it should be typed as `returns(T.untyped)`

**Actual behavior**
The method has `sig { void }`

**Additional information**
It's more important to be correct than being comprehensive but wrong, since sorbet will enforce the sig at run-time

I'm very excited about using `sord` to generate rbi files for `sorbet-typed`. If you need any help getting it to a reliable state, please feel free to let me know. I'll chime in where I can.

**Comment by AaronC81** [comment]
I'd agree that changing it to `returns(T.untyped)` sounds like a good change if no return type is given. Thank you!

**Comment by manhhung741** [comment]
Did you test against the test case I gave? I pulled master but it doesn't seem to fix the filed issue. Unless I miss any step to rebuild `exe/sord`

**Comment by AaronC81** [comment]
It's fixed for me, sorry - maybe try deleting the repo and pulling it again?

A clean copy of master gives me this signature:

```ruby
      # sord omit - no YARD return type given, using T.untyped
      sig { returns(T.untyped) }
      def changed_attribute_names_to_save(); end
```

(Please note that the fix isn't on RubyGems yet.)

**Comment by manhhung741** [comment]
Yeah, I'm cloning directly from github but somehow still doesn't work. I've tried to delete `sord` and clone again, still didn't work. Something must have been cached somewhere.
Anyway, I feel good that you're on top of it. It'll probably give more confidence if there are some tests.
```
      def changed_attribute_names_to_save(); end
      sig { void }
      def attributes_in_database(); end
      sig { void }
      def mutations_from_database(); end
      sig { void }
      def mutations_before_last_save(); end
```

**Comment by AaronC81** [comment]
That's really odd. The behaviour is tested here: https://github.com/AaronC81/sord/blob/master/spec/rbi_generator_spec.rb#L96-L129

**Comment by manhhung741** [comment]
👍 thanks for being on top of it. There should be a test where there are some comments for the function but not a return type comment, but all good.
