### ISSUE TITLE
Add flag to replace SORD_ERRORs with untyped

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#50]
**Is your feature request related to a problem? Please describe.**
I’d like to be able to automatically generate a valid rbi without needing any manual changes.

**Describe the solution you'd like to happen**

I’d like a flag, like --replace-errors-with-untyped, to automatically set T.untyped in place of SORD_ERRORs

**Comment by AaronC81** [comment]
Good suggestion. This is on master now; let me know if you find any issues with it!
