### ISSUE TITLE
RFC: Breaking the bulk of RBI generation out into a separate gem

### ISSUE THREAD

**Issue by AaronC81** [AaronC81/sord#71]
I had the idea that the RBI generation component of this gem could be broken out into its own gem with a polished interface. This would then ease the development of other RBI generator gems like Sord. (My main motivation for this is that I'd like to write a generator for Sequel models.) Sord could then use this gem for its generator.

Here's an example of how this interface could look:

```ruby
# You can use a traditional OOP style...
builder = RbiGenerator::Builder.new
mod = builder.root.create_module('MyModule')
mod.create_class('Foo')
bar = mod.create_class('Bar', superclass: 'Foo')
bar.create_method(
  :do_something_to_string,
  parameters: [['x', 'String']],
  returns: 'String'
)

# ...or a more Ruby-esque style, as constructors `yield_self` to their block
builder = RbiGenerator::Builder.new
builder.root.create_module('MyModule') do |mod|
  mod.create_class('Foo')
  mod.create_class('Bar', superclass: 'Foo') do |bar|
    bar.create_method(
      :do_something_to_string,
      parameters: [['x', 'String']],
      returns: 'String'
    )
  end
end
```

This gem could also double as a kind of 'build system for RBIs', in that it can invoke multiple scripts which generate RBIs and pass them all the same `RbiGenerator::Builder` instance, creating one final RBI file for all generators. If multiple generators create different methods for the same class, they are merged together. If they attempt to generate different signatures for the same method, it could handle conflict resolution somehow.

@connorshea - what are your thoughts on this?

**Comment by connorshea** [comment]
This'd be awesome 👍 Might be useful for sorbet-rails as well.

**Comment by connorshea** [comment]
You should maybe note that there'll need to be a way to set formatting rules when instantiating the builder, e.g. how many parameters are needed before turning the signature into a block.

**Comment by AaronC81** [comment]
Ah, yep, good point.

**Comment by manhhung741** [comment]
Hey that'd be useful. I was thinking about breaking down the generation code into a separate library as well lol

**Comment by manhhung741** [comment]
From my experience generating rbis. The parameter will need an arg_type argument
- keyrest
- rest
- block
See most of the generation logic I have here
https://github.com/chanzuckerberg/sorbet-rails/blob/master/lib/sorbet-rails/model_rbi_formatter.rb#L344

**Comment by manhhung741** [comment]
I also think it's preferable to not have nested module like
```
module A
  class B 
  end
end
```
This style is a lot simpler end easier to format
```
module A
end

class A::B
end
```

**Comment by AaronC81** [comment]
Great - I'll get cracking on doing this.

@manhhung741 - yeah, that's a good point, we'll need a way of specifying `**`, `*`, or `&`, though I suppose this could be implied from the name given and then removed when generating the `params` call.

Also, of those two module nesting styles, Sord uses the first because it makes namespace resolution easier. They aren't actually equivalent in how they behave:

This is fine...

```ruby
module M
  class A; end

  class B
    A # perfectly fine
  end
end
```

...but this causes errors:

```ruby
module M; end

class M::A; end

class M::B
  A # uninitialized constant M::B::A
end
```

This behaviour surprised me when writing Sord! It's not an issue if every type name you use is fully-qualified, but this definitely wasn't the case with Sord.

Still, the second style should certainly be an option.

**Comment by connorshea** [comment]
I’ve got tomorrow off work and I’d be happy to start hacking on this if you push whatever you’ve got to the repo (assuming you’ve got the base you want completed, I don’t want to interfere with the basic design you’ve got in mind).

**Comment by AaronC81** [comment]
Awesome, I've got a pretty good start so far, so I'll push soon! Should be
in the next few hours.

**Comment by AaronC81** [comment]
OK, I've put my current work up here: https://github.com/AaronC81/parlour

It's not got too much documentation yet but hopefully the README plus the Sorbet signatures should be enough.

As I am writing this it is 5am in my timezone, so I'll leave it there for now!

**Comment by manhhung741** [comment]
Thanks! I’m going to try this when I refactor the generation logic for
sorbet-rails.

**Comment by connorshea** [comment]
@AaronC81 As an aside, could you release a new version of sord based on the current master? (I didn't want to open a new issue just for this, sorry :P).

**Comment by AaronC81** [comment]
Crikey, yes, it has been a while, hasn't it - thanks for pointing this out!

I'll build and push current master to RubyGems as 0.8.0, then put a changelog together.

**Comment by AaronC81** [comment]
Closing this now, as Sord now uses Parlour and provides a Parlour plugin!
