### ISSUE TITLE
Range isn't handled properly if it doesn't have a type

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#77]
**Is your feature request related to a problem? Please describe.**
YARD uses Range in quite a few places in its docs and it doesn't supply a type for the Range (e.g. `Range<Integer>`), it just uses `Range`. 

```
sord_examples/yard.rbi:17064: Malformed type declaration. Generic class without type arguments Range https://srb.help/5004
       17064 |        sig { returns(Range) }
```

**Describe the solution you'd like**
`Range` should be set to `T::Range[T.untyped]` if there's no type defined for the value. I think the code is _supposed_ to do this, but `Range` isn't picked up by the `GENERIC_TYPE_REGEX`.

I assume this is true of most of the other [generics](https://sorbet.org/docs/stdlib-generics) supported by Sorbet.

**Comment by connorshea** [comment]
>Inside a sig, just writing `Array` or `Hash` will be treated as `T::Array[T.untyped]` and `T::Hash[T.untyped, T.untyped]` respectively.

I guess this note only applies to Arrays and Hashes?

**Comment by AaronC81** [comment]
Seems like it, though personally I think it would be good if the `T.untyped` default behaviour happened everywhere in Sorbet.

**Comment by AaronC81** [comment]
I'll open an issue in Sorbet asking about whether that could be implemented!

**Comment by AaronC81** [comment]
Raised here: https://github.com/sorbet/sorbet/issues/1220

**Comment by connorshea** [comment]
This is fixed, but the PR mentions that it won't be allowed in strict mode. I think we should probably just generate the full thing for all the enumerable types.
