### ISSUE TITLE
Implicit nilable when generating method signatures

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#86]
**Is your feature request related to a problem? Please describe.**

If I have a method like this:

```ruby
def initialize(text: nil, icon_url: nil); end
```

If there's no YARD documentation, the generated type signature looks like this:

```ruby
sig { params(text: T.untyped, icon_url: T.untyped).returns(T.untyped) }
def initialize(text: nil, icon_url: nil); end
```

I'm wondering if Sord should being able to assume the type is nilable given that the default value of the method is `nil`.

**Describe the solution you'd like**
If `nil` is the default value for a parameter, should Sord automatically generate the type as `T.nilable(T.untyped)` or is that outside its scope?

If it does that, it should do the same even if the YARD docs do specify a type, e.g.

```ruby
# In:
# ----
# @param text [String]
def initialize(text: nil); end

# Out:
# ----
sig { params(text: T.nilable(String)).returns(T.untyped)
def initialize(text: nil); end
```

**Comment by AaronC81** [comment]
I'd say this is reasonably within the scope of Sord, since it has an awareness of defaults even for undocumented methods thanks to the YARD database.

I think `T.untyped` already includes `nil`, but for other types like in your second example, this could be extraordinarily useful! I rarely add the `, nil` to my YARD types, which becomes much more of an issue when static typing is involved.

**Comment by connorshea** [comment]
Here's a test for this:
```ruby
  it 'marks variables with default nil as nilable' do
    YARD.parse_string(<<-RUBY)
      class A
        # @param [String] a
        # @return [void]
        def x(a: nil, b: nil); end

        # @param [String] a
        # @return [void]
        def y(a = nil); end
      end
    RUBY

    expect(subject.generate.strip).to eq fix_heredoc(<<-RUBY)
      # typed: strong
      class A
        sig { params(a: T.nilable(String), b: T.untyped).void }
        def x(a: nil, b: nil); end

        sig { params(a: T.nilable(String)).void }
        def y(a = nil); end
      end
    RUBY
  end
```

I think I discovered a bug with Sord when writing this. It seems to not detect the `# @param [String] a` part, and returns T.untyped for `a` in the signature for `x`.

This is the diff RSpec returns:

```diff
@@ -1,9 +1,11 @@
 # typed: strong
 class A
-  sig { params(a: T.nilable(String), b: T.untyped).void }
+  # sord omit - no YARD type given for "a:", using T.untyped
+  # sord omit - no YARD type given for "b:", using T.untyped
+  sig { params(a: T.untyped, b: T.untyped).void }
   def x(a: nil, b: nil); end
 
-  sig { params(a: T.nilable(String)).void }
+  sig { params(a: String).void }
   def y(a = nil); end
 end
```

**Comment by connorshea** [comment]
Here's a test that tests the parameters specifically:

```ruby
it 'correctly parses methods with all kinds of parameters' do
    YARD.parse_string(<<-RUBY)
      class A
        # @param [String] a
        # @param [String] b
        # @param [String] c
        # @param [String] d
        # @return [void]
        def x(a, b = 'Foo', c: 'Bar', d:); end
      end
    RUBY

    expect(subject.generate.strip).to eq fix_heredoc(<<-RUBY)
      # typed: strong
      class A
        sig do
          params(
            a: String,
            b: String,
            c: String,
            d: String
          ).void
        end
        def x(a, b = 'Foo', c: 'Bar', d:); end
      end
    RUBY
  end
```

Here's the test result on the current `master` branch:

```diff
@@ -1,11 +1,13 @@
 # typed: strong
 class A
+  # sord omit - no YARD type given for "c:", using T.untyped
+  # sord omit - no YARD type given for "d:", using T.untyped
   sig do
     params(
       a: String,
       b: String,
-      c: String,
-      d: String
+      c: T.untyped,
+      d: T.untyped
     ).void
   end
   def x(a, b = 'Foo', c: 'Bar', d:); end
```

This might actually be a bug in Parlour, I don't know.

**Comment by AaronC81** [comment]
I believe this should be implemented now - I think I've got the logic for determining whether we need to wrap in `T.nilable` correct.
