### ISSUE TITLE
Escaped symbol arguments aren't handled correctly

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#9]
Escaped symbols, or string-symbols, or as I like to call them, 'abominations', don't get sent through to the generated file properly.

Input:

```ruby
def create_server(name, region = :'eu-central')
  # code
end
```

Generated rbi method:

```ruby
def create_server(name, region = eu-central) end
```

**Comment by AaronC81** [comment]
It looks like this may actually be an issue with YARD itself.

Take the following example code:

```
module Example
  class Foo
    def bar(x = :'abomination')
      3
    end
  end
end
```

It appears that the YARD registry (assigned to `r` here) doesn't include the `:` and apostrophes around the identifier:

```
irb(main):012:0> r.all(:class).first.meths.first.parameters
=> [["x", "abomination"]]
```

**Comment by AaronC81** [comment]
The generated YARD HTML docs also show the same issue!

![image](https://user-images.githubusercontent.com/3321773/59962389-b6acba80-94dc-11e9-9a65-27f3104577ed.png)

**Comment by AaronC81** [comment]
This has now been fixed in YARD (https://github.com/lsegal/yard/issues/1256).
